CREATE DATABASE LosGatos
GO

GO
CREATE TABLE [dbo].[Raca](
	[RacaId] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK_Raca] PRIMARY KEY CLUSTERED 
(
	[RacaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UX_Breed] UNIQUE NONCLUSTERED 
(
	[Nome] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

Go
CREATE TABLE [dbo].[Gato](
	[GatoId] [int] IDENTITY(1,1) NOT NULL,
	[RacaId] [int] NOT NULL,
	[Nome] [nvarchar](200) NOT NULL,
	[Idade] [int] NOT NULL,
 CONSTRAINT [PK_Cat] PRIMARY KEY CLUSTERED 
(
	[GatoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Gato]  WITH CHECK ADD  CONSTRAINT [FK_Gato_Raca] FOREIGN KEY([RacaId])
REFERENCES [dbo].[Raca] ([RacaId])
GO
ALTER TABLE [dbo].[Gato] CHECK CONSTRAINT [FK_Gato_Raca]
GO
